name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/westep_users/dist"
          strip_components: 1 # dist papkasini o'zini emas, ichidagi fayllarni tarqatadi

      - name: Send Telegram Notification
        if: always() # Deploy muvaffaqiyatli bo'lsa ham, xato bo'lsa ham xabar boradi
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ${{ job.status == 'success' && '🚀 **Yangi Deploy!**' || '❌ **Deployda Xatolik!**' }}
            
            **Loyiha:** `${{ github.repository }}`
            **Commit:** `${{ github.event.head_commit.message }}`
            **Muallif:** @${{ github.actor }}
            **Status:** ${{ job.status == 'success' && '✅ Muvaffaqiyatli' || '⚠️ Xato yuz berdi' }}
            
            [O'zgarishlarni ko'rish](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
